/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class craigacp_mitoolbox_MIToolbox */

#ifndef _Included_craigacp_mitoolbox_MIToolbox
#define _Included_craigacp_mitoolbox_MIToolbox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     craigacp_mitoolbox_MIToolbox
 * Method:    checkedhx
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_craigacp_mitoolbox_MIToolbox_checkedhx
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     craigacp_mitoolbox_MIToolbox
 * Method:    checkedhxcondy
 * Signature: ([I[I)D
 */
JNIEXPORT jdouble JNICALL Java_craigacp_mitoolbox_MIToolbox_checkedhxcondy
  (JNIEnv *, jclass, jintArray, jintArray);

/*
 * Class:     craigacp_mitoolbox_MIToolbox
 * Method:    checkedhxy
 * Signature: ([I[I)D
 */
JNIEXPORT jdouble JNICALL Java_craigacp_mitoolbox_MIToolbox_checkedhxy
  (JNIEnv *, jclass, jintArray, jintArray);

/*
 * Class:     craigacp_mitoolbox_MIToolbox
 * Method:    checkedmi
 * Signature: ([I[I)D
 */
JNIEXPORT jdouble JNICALL Java_craigacp_mitoolbox_MIToolbox_checkedmi
  (JNIEnv *, jclass, jintArray, jintArray);

/*
 * Class:     craigacp_mitoolbox_MIToolbox
 * Method:    checkedcmi
 * Signature: ([I[I[I)D
 */
JNIEXPORT jdouble JNICALL Java_craigacp_mitoolbox_MIToolbox_checkedcmi
  (JNIEnv *, jclass, jintArray, jintArray, jintArray);

/*
 * Class:     craigacp_mitoolbox_MIToolbox
 * Method:    checkedRenyiEntropy
 * Signature: (D[I)D
 */
JNIEXPORT jdouble JNICALL Java_craigacp_mitoolbox_MIToolbox_checkedRenyiEntropy
  (JNIEnv *, jclass, jdouble, jintArray);

/*
 * Class:     craigacp_mitoolbox_MIToolbox
 * Method:    checkedRenyiJointEntropy
 * Signature: (D[I[I)D
 */
JNIEXPORT jdouble JNICALL Java_craigacp_mitoolbox_MIToolbox_checkedRenyiJointEntropy
  (JNIEnv *, jclass, jdouble, jintArray, jintArray);

/*
 * Class:     craigacp_mitoolbox_MIToolbox
 * Method:    checkedRenyiMI
 * Signature: (D[I[I)D
 */
JNIEXPORT jdouble JNICALL Java_craigacp_mitoolbox_MIToolbox_checkedRenyiMI
  (JNIEnv *, jclass, jdouble, jintArray, jintArray);

/*
 * Class:     craigacp_mitoolbox_MIToolbox
 * Method:    checkedwhx
 * Signature: ([I[D)D
 */
JNIEXPORT jdouble JNICALL Java_craigacp_mitoolbox_MIToolbox_checkedwhx
  (JNIEnv *, jclass, jintArray, jdoubleArray);

/*
 * Class:     craigacp_mitoolbox_MIToolbox
 * Method:    checkedwhxcondy
 * Signature: ([I[I[D)D
 */
JNIEXPORT jdouble JNICALL Java_craigacp_mitoolbox_MIToolbox_checkedwhxcondy
  (JNIEnv *, jclass, jintArray, jintArray, jdoubleArray);

/*
 * Class:     craigacp_mitoolbox_MIToolbox
 * Method:    checkedwhxy
 * Signature: ([I[I[D)D
 */
JNIEXPORT jdouble JNICALL Java_craigacp_mitoolbox_MIToolbox_checkedwhxy
  (JNIEnv *, jclass, jintArray, jintArray, jdoubleArray);

/*
 * Class:     craigacp_mitoolbox_MIToolbox
 * Method:    checkedwmi
 * Signature: ([I[I[D)D
 */
JNIEXPORT jdouble JNICALL Java_craigacp_mitoolbox_MIToolbox_checkedwmi
  (JNIEnv *, jclass, jintArray, jintArray, jdoubleArray);

/*
 * Class:     craigacp_mitoolbox_MIToolbox
 * Method:    checkedwcmi
 * Signature: ([I[I[I[D)D
 */
JNIEXPORT jdouble JNICALL Java_craigacp_mitoolbox_MIToolbox_checkedwcmi
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
